# fly.toml file generated for chatie-talkie on 2023-05-13T19:43:19+07:00

app = "chatie-talkie"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sin"

[build]
  builder = "heroku/buildpacks:20"

[env]
  DB_HOST = "aws.connect.psdb.cloud"
  DB_NAME = "chatie-talkie"
  DB_PASSWORD = "pscale_pw_2dyXvWhrhMVVqRqhykxHCkwchXlpnaq2DJVwAcFozg8"
  DB_USERNAME = "y113g823k9h24sbga8uk"
  NODE_ENV = "production"
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
